services:
  vncserver:
    build:
      context: .
      target: vncserver
      args:
        proxy: "${proxy:-}"
        vncpasswd: "${vncpasswd:-}"
    restart: "${restart:-no}"
    environment:
      - XSERVER
      - VNCSERVER
    ports:
      #- "22:22"
      - published: ${XSERVER:-6001}
        target: 6001
        protocol: tcp
        mode: host
      - published: ${VNCSERVER:-5901}
        target: 5901
        protocol: tcp
        mode: host
    command:
    - tail
    - "-f"
    - /dev/null
