version: '3.7'

services:
  vncserver:
    build:
      context: .
      target: vncserver
      args:
        proxy: "${proxy:-}"
    #restart: always
    ports:
      #- "22:22"
      - "6001:6001"
      - "5901:5901"
    command:
    - tail
    - "-f"
    - /dev/null
