services:
  vncserver:
    build:
      context: .
      target: vncserver
      args:
        proxy: "${proxy:-}"
        vncpasswd: "${vncpasswd:-}"
    restart: "${restart:-no}"
    ports:
      #- "22:22"
      - "6001:6001"
      - "5901:5901"
    command:
    - tail
    - "-f"
    - /dev/null
