#!/bin/sh

echo "DISPLAY=$DISPLAY" > $HOME/.display
echo 'export DISPLAY' >> $HOME/.display

if [ -f $HOME/.Xresources ]; then
    xrdb $HOME/.Xresources
fi
xsetroot -solid grey
#startxfce4 < /dev/null > /dev/null 2>&1 &
startxfce4 < /dev/null &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1

xhost +

/etc/X11/Xsession
